In [1]:
import numpy as np

# Numpy Operations

## Arithmetic operations

Arithmetic operations on ndarrays are **element-wise** (point-to-point).

Note, that beside [Arithmetic functions](https://numpy.org/doc/stable/reference/routines.math.html#arithmetic-operations), numpy sumply a great variaty of [Mathematical functions](https://numpy.org/doc/stable/reference/routines.math.html)

Lets have next 2 arrays:

In [2]:
arr1 = np.arange(5)
print(f'arr1: {arr1}, {arr1.dtype}')


arr1: [0 1 2 3 4], int64


In [3]:
arr2 = np.full(5,2)
print(f'arr2: {arr2}, {arr2.dtype}')

arr2: [2 2 2 2 2], int64


### Addition

We can use the '+' operator as a shortcut to np.add()

In [4]:
# add array with constant:
print(f'arr1: {arr1}')
arr1+1

arr1: [0 1 2 3 4]


array([1, 2, 3, 4, 5])

In [5]:
# add two arrays
print(f'arr1: {arr1}')
print(f'arr2: {arr2}')
arr1 + arr2

arr1: [0 1 2 3 4]
arr2: [2 2 2 2 2]


array([2, 3, 4, 5, 6])

### Subtraction

We can use the '-' operator as a shortcut to np.subtract()

In [6]:
# subtract array with constant:
print(f'arr1: {arr1}')
arr1-1

arr1: [0 1 2 3 4]


array([-1,  0,  1,  2,  3])

In [7]:
# subtract two arrays
print(f'arr1: {arr1}')
print(f'arr2: {arr2}')
arr1 - arr2

arr1: [0 1 2 3 4]
arr2: [2 2 2 2 2]


array([-2, -1,  0,  1,  2])

### Multiplication

We can use the '*' operator as a shortcut to np.multiply()

In [8]:
# multiply array with constant:
print(f'arr1: {arr1}')
arr1*3

arr1: [0 1 2 3 4]


array([ 0,  3,  6,  9, 12])

In [9]:
# multiply two arrays
print(f'arr1: {arr1}')
print(f'arr2: {arr2}')
arr1 * arr2

arr1: [0 1 2 3 4]
arr2: [2 2 2 2 2]


array([0, 2, 4, 6, 8])

### Division

We can use the '/' operator as a shortcut to np.divide()

In [10]:
# divide array with constant:
print(f'arr1: {arr1}')
arr1/3

arr1: [0 1 2 3 4]


array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333])

In [11]:
# divide two arrays
print(f'arr1: {arr1}')
print(f'arr2: {arr2}')
arr1 / arr2

arr1: [0 1 2 3 4]
arr2: [2 2 2 2 2]


array([0. , 0.5, 1. , 1.5, 2. ])

## Comparison and Logic Operations

### Arrays Comparison

Comparison Operations on ndarrays are **element-wise** (point-to-point).

They return an array of same shape with Boolean values.

Reference: [Comparison functions](https://numpy.org/doc/stable/reference/routines.logic.html#comparison)

In [12]:
### Equal (==) or np.equal() with constant
print(arr1)
print(arr1 == 1)
# print(np.equal(arr1,1))

[0 1 2 3 4]
[False  True False False False]


In [13]:
### Equal (==) or np.equal() with another array
print(arr1)
print(arr2)
print(arr1 == arr2)
# print(np.equal(arr1,arr2))

[0 1 2 3 4]
[2 2 2 2 2]
[False False  True False False]


In [14]:
### Not equal (!=) or np.not_equal() with constant
print(arr1)
print(arr1 != 1)
# print(np.not_equal(arr1,1))

[0 1 2 3 4]
[ True False  True  True  True]


In [15]:
### Not equal (!=) or np.not_equal() with another array
print(arr1)
print(arr2)
print(arr1 != arr2)
# print(np.not_equal(arr1,arr2))

[0 1 2 3 4]
[2 2 2 2 2]
[ True  True False  True  True]


In [16]:
### Greater (>) or np.greater() with constant
print(arr1)
print(arr1 > 1)
# print(np.greater(arr1,1))

[0 1 2 3 4]
[False False  True  True  True]


In [17]:
### Greater or equal (>=) or np.greater_equal() with another array
print(arr1)
print(arr2)
print(arr1 >= arr2)
# print(np.greater_equal(arr1,arr2))

[0 1 2 3 4]
[2 2 2 2 2]
[False False  True  True  True]


In [18]:
### Less (<) or np.less() with constant
print(arr1)
print(arr1 < 1)
# print(np.less(arr1,1))

[0 1 2 3 4]
[ True False False False False]


In [19]:
### Less or equal (<=) or np.less_equal() with another array
print(arr1)
print(arr2)
print(arr1 <= arr2)
# print(np.less_equal(arr1,arr2))

[0 1 2 3 4]
[2 2 2 2 2]
[ True  True  True False False]


### Logical operations

Logical operations on ndarrays are **element-wise** (point-to-point).

They return an array of same shape with Boolean values.

Logical operations are [commutative](https://en.wikipedia.org/wiki/Commutative_property)

Reference: [Logical operations](https://numpy.org/doc/stable/reference/routines.logic.html#logical-operations)

#### Logical AND

<img src="../images/logical_and.png">

[np.logical_and()](https://numpy.org/doc/stable/reference/generated/numpy.logical_and.html#numpy-logical-and) - Compute the truth value of x1 AND x2 element-wise.

The & operator can be used as a shorthand for np.logical_and() **only on boolean values/ndarrays**.

In [20]:
# logical and between 2 booleans:
True & False
# np.logical_and(True, False)

False

In [21]:
# logical and between 2 boolean arrays:
print(f'arr1: {arr1}')
print(f'arr2: {arr2}','\n')

x = arr1>2
y = arr2>1
print(f'x: {x}')
print(f'y: {y}','\n')

print(f'x&y: {x&y}')
# print(np.logical_and(x,y))


arr1: [0 1 2 3 4]
arr2: [2 2 2 2 2] 

x: [False False False  True  True]
y: [ True  True  True  True  True] 

x&y: [False False False  True  True]


In [22]:
# logical and between 2 scalars:
# note that a value=0 is interpreted as False,
# and a value != 0 is interpreted as True 

print(np.logical_and(1, -92349))
print(np.logical_and(1, 0))

True
False


#### Logical OR

<img src="../images/logical_or.png">

[np.logical_or()](https://numpy.org/doc/stable/reference/generated/numpy.logical_or.html#numpy-logical-or) - Compute the truth value of x1 OR x2 element-wise.

The | operator can be used as a shorthand for np.logical_or() **only on boolean values/ndarrays**.

In [23]:
# logical or between 2 booleans:
True | False
# np.logical_or(True, False)

True

In [24]:
# logical or between 2 boolean arrays:
print(f'arr1: {arr1}')
print(f'arr2: {arr2}','\n')

x = arr1>2
y = arr2>1
print(f'x: {x}')
print(f'y: {y}','\n')

print(f'x|y: {x|y}')
# print(np.logical_or(x,y))


arr1: [0 1 2 3 4]
arr2: [2 2 2 2 2] 

x: [False False False  True  True]
y: [ True  True  True  True  True] 

x|y: [ True  True  True  True  True]


In [25]:
# logical or between 2 scalars:
print(np.logical_or(1, -92349))
print(np.logical_or(1, 0))
print(np.logical_or(0, 0))

True
True
False


#### Logical NOT

<img src="../images/logical_not.png">

[np.logical_not()](https://numpy.org/doc/stable/reference/generated/numpy.logical_not.html#numpy-logical-not) - Compute the truth value of NOT x element-wise.

In [26]:
# logical not on one boolean:
np.logical_not(True)

False

In [27]:
# logical not on boolean array:
print(f'arr1: {arr1}')

x = arr1>2
print(f'x: {x}')

print(np.logical_not(x,y))


arr1: [0 1 2 3 4]
x: [False False False  True  True]
[ True  True  True False False]


In [28]:
# logical not on  scalar:
print(np.logical_not(-92349))
print(np.logical_not(1))
print(np.logical_not(0))

False
False
True


In [29]:
print(arr1)
print(arr2)

[0 1 2 3 4]
[2 2 2 2 2]


### Truth value testing

[np.all()](https://numpy.org/doc/stable/reference/generated/numpy.all.html#numpy.all) - Test whether all array elements along a given axis evaluate to True.

[np.any()](https://numpy.org/doc/stable/reference/generated/numpy.any.html#numpy.any) - Test whether any array element along a given axis evaluates to True.

In [30]:
print(f'arr1>2: {arr1>2}')

print(np.all(arr1>2))
print(np.any(arr1>2))

arr1>2: [False False False  True  True]
False
True
