In [1]:
import numpy as np

# Numpy Arrays: Reshape and Transpose

## Reshape

Remember that **shape of an array** is the number of elements in each dimension.

NumPy array reshape() method is used to change the shape of the NumPy array without changing its data. Reshaping allows us to add or remove dimensions in an array.

### Basic Syntax

`numpy.reshape(a, newshape, order='C')`

or:

`ndarray.reshape(newshape, order='C')`		

Where:
- newshape can be an integer or tupple. 
  - If it is an integer, then the result will be a 1-D array of that length.
  - If it is a tupple, then the result will be an array with the given shape. 
	Note that the new shape should be compatible with the original shape. I.e. 
	we can not reshape an array with shape (9, ) to new shape (2,5) as 
	the number of elements will not be the same.
- order:
  - if order='C': convert array along the row 
  - if order='F': convert array along the column 

Return Value:

reshape() returns a new array without changing the original one.

Reference: [numpy.reshape](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html)

### Examples

In [2]:
###  Convert an array from 1-D to 2-D:
arr = np.arange(6)
print(arr)

arr.reshape(2,3)

[0 1 2 3 4 5]


array([[0, 1, 2],
       [3, 4, 5]])

In [3]:
### Convert an array from 1-D to 3-D:
arr = np.arange(2*3*4)
print(arr)

arr.reshape((2,3,4))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [4]:
### Change dimensions 
# note, that this is not the same as array transpose(), which we'll discuss firther.

arr = np.arange(6).reshape(2,3)
print(arr)

arr.reshape(3,2)

[[0 1 2]
 [3 4 5]]


array([[0, 1],
       [2, 3],
       [4, 5]])

In [5]:
### When -1 is used in the dimension, the value is inferred from the length of the array and remaining dimensions.

arr = np.arange(6)
print(arr)

arr.reshape((3,-1))

[0 1 2 3 4 5]


array([[0, 1],
       [2, 3],
       [4, 5]])

In [6]:
### Reshape 1-D to 2-D Array along Column wise with order ‘F’

arr = np.arange(6)
print(arr)

arr.reshape(2,3, order='F')

[0 1 2 3 4 5]


array([[0, 2, 4],
       [1, 3, 5]])

In [7]:
### Reshape 2-D array to 1-D:
arr = np.ones((2,3))
print(arr)

arr.reshape(6)

# equivalent as above
# arr.reshape((6,))


[[1. 1. 1.]
 [1. 1. 1.]]


array([1., 1., 1., 1., 1., 1.])

## Ravel

NumPy array ravel() method is used to flattened an array.

### Basic Syntax

`numpy.ravel(a, order='C')`

or 

`ndarray.ravel([order])`

if order='C' flaten by rows

if order='F' flaten by columns


### Examples

In [8]:
# Ravel 2-D to 1-D array by rows:

a2d = np.arange(6).reshape(2,3)
print(a2d)

a2d.ravel()

[[0 1 2]
 [3 4 5]]


array([0, 1, 2, 3, 4, 5])

In [9]:
# Ravel 2-D to 1-D array by columns:

a2d = np.arange(6).reshape(2,3)
print(a2d)

a2d.ravel(order='F')

[[0 1 2]
 [3 4 5]]


array([0, 3, 1, 4, 2, 5])

## Transpose

Numpy allows us to transpose any array, as in Matrix Transposition.

In linear algebra, the transpose of a matrix is an operator which flips a matrix over its diagonal. That is, it switches the row and column indices of the matrix $A$ by producing another matrix, often denoted by $A^T$

<img src="../images/MatrixTransposition.webp" alt="Matrix Transposition">

With `transpose()` method we can reverse or permute the axes of an array, making any kind of transpositions.

### Basic Syntax

`numpy.transpose(a, axes=None)`

or

`ndarray.transpose(*axes)`

*Parameters*:
**axes**: None, tuple of ints, or n ints

- None or no argument: reverses the order of the axes.

- tuple of ints: i in the j-th place in the tuple means a’s i-th axis becomes a.transpose()’s j-th axis.

- n ints: same as an n-tuple of the same ints (this form is intended simply as a “convenience” alternative to the tuple form)

*Returns*: a view of array, without changing it.

**For a 1-D array this has no effect, as a transposed vector is simply the same vector**

Reference: https://numpy.org/doc/stable/reference/generated/numpy.ndarray.transpose.html#numpy.ndarray.transpose


Note that for ndarray.transpose(), without arguments, we can use the shortcut object ndarray.T
which do the same.


### Examples

In [10]:
### no effect on 1D (Vector) array:
arr = np.arange(6)
print(arr)

arr.transpose()

[0 1 2 3 4 5]


array([0, 1, 2, 3, 4, 5])

2D (Matrix) transpose - no arguments

<img src="../images/numpy_transpose_function.png">

In [11]:
### 2D (Matrix) transpose - no arguments
arr = np.arange(6).reshape(3,2)
print(arr)

arr.transpose()

[[0 1]
 [2 3]
 [4 5]]


array([[0, 2, 4],
       [1, 3, 5]])

In [12]:
### 2D (Matrix) transpose - with T object:

arr = np.arange(6).reshape(3,2)
print(arr)

arr.T

[[0 1]
 [2 3]
 [4 5]]


array([[0, 2, 4],
       [1, 3, 5]])

In [13]:
### Change position of axes with tuple as argument:
arr = np.arange(24).reshape(2,3,4)
print(arr)

arr.transpose((0,2,1))

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


array([[[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]],

       [[12, 16, 20],
        [13, 17, 21],
        [14, 18, 22],
        [15, 19, 23]]])