In [1]:
import numpy as np

# Numpy Arrays: Reshape and Transpose

## Reshape

Remember that **shape of an array** is the number of elements in each dimension.

NumPy array reshape() method is used to change the shape of the NumPy array without changing its data. Reshaping allows us to add or remove dimensions in an array.

### Basic Syntax

`numpy.reshape(a, newshape, order='C')`

or:

`ndarray.reshape(newshape, order='C')`		

Where:
- newshape can be an integer or tupple. 
  - If it is an integer, then the result will be a 1-D array of that length.
  - If it is a tupple, then the result will be an array with the given shape. 
	Note that the new shape should be compatible with the original shape. I.e. 
	we can not reshape an array with shape (9, ) to new shape (2,5) as 
	the number of elements will not be the same.
- order:
  - if order='C': convert array along the row 
  - if order='F': convert array along the column 

Return Value:

reshape() returns a new array without changing the original one.

Reference: [numpy.reshape](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html)

### Examples

In [14]:
###  Convert an array from 1-D to 2-D:
arr = np.arange(6)
print(arr)

arr.reshape(2,3)

[0 1 2 3 4 5]


array([[0, 1, 2],
       [3, 4, 5]])

In [12]:
### Convert an array from 1-D to 3-D:
arr = np.arange(2*3*4)
print(arr)

arr.reshape((2,3,4))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [19]:
### Change dimensions 
# note, that this is not the same as array transpose(), which we'll discuss firther.

arr = np.arange(6).reshape(2,3)
print(arr)

arr.reshape(3,2)

[[0 1 2]
 [3 4 5]]


array([[0, 1],
       [2, 3],
       [4, 5]])

In [21]:
### When -1 is used in the dimension, the value is inferred from the length of the array and remaining dimensions.

arr = np.arange(6)
print(arr)

arr.reshape((3,-1))

[0 1 2 3 4 5]


array([[0, 1],
       [2, 3],
       [4, 5]])

In [23]:
### Reshape 1-D to 2-D Array along Column wise with order ‘F’

arr = np.arange(6)
print(arr)

arr.reshape(2,3, order='F')

[0 1 2 3 4 5]


array([[0, 2, 4],
       [1, 3, 5]])

In [29]:
### Reshape 2-D array to 1-D:
arr = np.ones((2,3))
print(arr)

arr.reshape(6)

# equivalent as above
# arr.reshape((6,))


[[1. 1. 1.]
 [1. 1. 1.]]


array([1., 1., 1., 1., 1., 1.])

## Ravel

NumPy array ravel() method is used to flattened an array.

### Basic Syntax

`numpy.ravel(a, order='C')`

or 

`ndarray.ravel([order])`

if order='C' flaten by rows

if order='F' flaten by columns


### Examples

In [36]:
# Ravel 2-D to 1-D array by rows:

a2d = np.arange(6).reshape(2,3)
print(a2d)

a2d.ravel()

[[0 1 2]
 [3 4 5]]


array([0, 1, 2, 3, 4, 5])

In [37]:
# Ravel 2-D to 1-D array by columns:

a2d = np.arange(6).reshape(2,3)
print(a2d)

a2d.ravel(order='F')

[[0 1 2]
 [3 4 5]]


array([0, 3, 1, 4, 2, 5])

## Transpose

Numpy allows us to transpose any array, as in Matrix Transposition.

In linear algebra, the transpose of a matrix is an operator which flips a matrix over its diagonal. That is, it switches the row and column indices of the matrix $A$ by producing another matrix, often denoted by $A^T$

<img src="../images/MatrixTransposition.webp" alt="Matrix Transposition">