# The numpy array

In [2]:
import numpy as np

### Create N dimensional arrays:

By literal - note that the number of opening squares equals the dimension

In [3]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

Create array filled with random values: __np.empty__ of type __np.int8__

In [4]:
b = np.empty( (3,2), dtype=np.int8  )
b

array([[-120,  -85],
       [ -72,  -92],
       [-121,  127]], dtype=int8)

Create array by __np.arange()__ method (quite simmilar to python's __range()__)

In [5]:
b = np.arange(0,21,2)
b

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

### Simple indexing

In [6]:
a[1][2]

6

### Basic numpy properties and methods

The number of axes (dimensions) of the array: __a.ndim__

In [7]:
a = np.array([[1,2,3],[4,5,6]])
a.ndim

2

Tuple of integers indicating the size of the array in each dimension: __ndarray.shape__

In [8]:
a = np.array([[1,2,4],[4,5,6]])
a.shape

(2, 3)

In [9]:
b = np.array([[1,2],[3,4],[5,6]])
b.shape

(3, 2)

Total number of elements of the array: __a.size__

In [10]:
a = np.array([[1,2,3],[4,5,6]])
a.size

6

The size in bytes of each element of the array: __a.itemsize__

In [11]:
a = np.array([[1,2,3],[4,5,6]])
a.itemsize

8

### Array Manipulations

##### Flatten the array

In [12]:
a = np.array([[1,2,3],[4,5,6]])
a.ravel()

array([1, 2, 3, 4, 5, 6])

#### reshaping arrays: __np.reshape()__

In [19]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a.shape

(3, 3)

In [14]:
a.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [15]:
a.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

### Arrays Algebra (Element Wise)

In [16]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2,3],[4,5,6]])

a+b

array([[ 2,  4,  6],
       [ 8, 10, 12]])

#### matrix product: __dot()__ 

In [17]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2],[3,4],[5,6]])

a.dot(b)

array([[22, 28],
       [49, 64]])

In [18]:
b.dot(a)

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])