In [3]:
import numpy as np

# Numpy Array Manipulations with Visualization

<img src="../images/1d_2d_3d_arrays.png" style="width:50vw; background:#FFF;border:20px solid #FFF;">

## Indexing

Array indexing and slicing is similat to Python indexing and slicing lists.


But in a a multidimensional array, we access items using comma-separated indices. 


### 1D array indexing and slicing

<img src="../images/1Darray-slice.png" style="width:50vw; background:#FFF;border:20px solid #FFF;">


In [4]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [5]:
arr[0]

1

In [7]:
# negative indexing also works:
arr[-1]

3

When we slice an array using [start:end] the result is a "view" - it don't store the data and reflect the changes in the original array if it happens to get changed after being indexed.

In [15]:
s = arr[0:2]
print(arr)
print(s)

[9 2 3]
[9 2]


In [14]:
arr[0] = 9

print(arr)
print(s)

[9 2 3]
[9 2]


### 2D Array indexing and slicing

<img src="../images/2D_slicing.png" style="width:50vw; background:#FFF;border:20px solid #FFF;">

In [17]:
a2d = np.arange(1,13).reshape(3,4)
print(a2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [20]:
a2d[:,2]

array([ 3,  7, 11])

### 3D Array indexing and slicing

<img src="../images/3D_Array_Props.png" style="width:50vw; background:#FFF;border:20px solid #FFF;">

In [31]:
a3d = np.arange(1,25).reshape(3,4,2)
a3d

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16]],

       [[17, 18],
        [19, 20],
        [21, 22],
        [23, 24]]])

In [33]:
a3d[0,0,0]

1

In [36]:
a3d[1,2,1]

14