In [3]:
import numpy as np

# Numpy Array Manipulations with Visualization

<img src="../images/1d_2d_3d_arrays.png" style="width:50vw; background:#FFF;border:20px solid #FFF;">

## Indexing

Array indexing and slicing is similat to Python indexing and slicing lists.


But in a a multidimensional array, we access items using comma-separated indices. 

When we slice an array using [start:end] the result is a "view" - it don't store the data and reflect the changes in the original array if it happens to get changed after being indexed.


### 1D array indexing and slicing

<img src="../images/1Darray-slice.png" style="width:50vw; background:#FFF;border:20px solid #FFF;">

**Indexing**: array[n]

n >= 0 => get n+1 element, from left to right

n <= -1 => get n element, from right to left 


**Slicing**: arr[start:stop:step]

start = index of start element. Default = beginning of array.

stop -1 = index of last element. Default = end of array (inclusive)

step   = the step to increment indexes on slice. Optional. Default 1.


In [38]:
a1 = np.arange(1,10)
print(a1)

print("\npositive index - from left to right - a1[1]")
print(a1[1])

print("\nnegative index - from right to left - a1[-1]")
print(a1[-1])

print("\nget elements with indexes 0 upto 3 (excluded) - a1[0:3]")
print(a1[0:3])

print("\nget all elements - a1[:]")
print(a1[:])

print("\nget all elements, without the last one - a1[:-1]")
print(a1[:-1])

print("\nslicing with step - a1[0:9:2]")
print(a1[0:9:2])

print("\nslicing with step - backwards - a1[-1::-2]")
print(a1[-1::-2])

[1 2 3 4 5 6 7 8 9]

positive index - from left to right - a1[1]
2

negative index - from right to left - a1[-1]
9

get elements with indexes 0 upto 3 (excluded) - a1[0:3]
[1 2 3]

get all elements - a1[:]
[1 2 3 4 5 6 7 8 9]

get all elements, without the last one - a1[:-1]
[1 2 3 4 5 6 7 8]

slicing with step - a1[0:9:2]
[1 3 5 7 9]

slicing with step - backwards - a1[-1::-2]
[9 7 5 3 1]


When we slice an array using [start:end] the result is a "view" - it don't store the data and reflect the changes in the original array if it happens to get changed after being indexed.

In [15]:
s = arr[0:2]
print(arr)
print(s)

[9 2 3]
[9 2]


In [14]:
arr[0] = 9

print(arr)
print(s)

[9 2 3]
[9 2]


### 2D Array indexing and slicing

<img src="../images/2D_slicing.png" style="width:50vw; background:#FFF;border:20px solid #FFF;">

**indexing**: matrix[i,j]

i - index rows

j - index columns

**slicing**: matrix[slice_row, slice_col]

In [17]:
a2d = np.arange(1,13).reshape(3,4)
print(a2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [20]:
a2d[:,2]

array([ 3,  7, 11])

### 3D Array indexing and slicing

<img src="../images/3D_Array_Props.png" style="width:50vw; background:#FFF;border:20px solid #FFF;">

**indexing**: a3d[ax0,ax1,ax2]


**slicing**: matrix[ax0_slice, ax1_slice,ax2_slice]

In [31]:
a3d = np.arange(1,25).reshape(3,4,2)
a3d

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16]],

       [[17, 18],
        [19, 20],
        [21, 22],
        [23, 24]]])

In [33]:
a3d[0,0,0]

1

In [36]:
a3d[1,2,1]

14

### Nympy indexing vs chaining

In [37]:

a1 = np.arange(1,28).reshape(3,3,3)
SIZE = 1_000_000

def multidim_index_tuple():
  for i in range(SIZE):
    x = a1[1,1,1]

def multidim_index_chained():
  for i in range(SIZE):
    x = a1[1][1][1]



%time multidim_index_tuple()
%time multidim_index_chained()

CPU times: user 246 ms, sys: 0 ns, total: 246 ms
Wall time: 265 ms
CPU times: user 405 ms, sys: 0 ns, total: 405 ms
Wall time: 405 ms


### Boolean Indexing

We can select certain values from a numpy array, if we mask it with a Boolean array (True/False values) with the **same shape**

<img src="../images/BooleanIndexing.png" style="width:60vw; background:#FFF;border:20px solid #FFF;">

In [39]:
# this is the original array:
a = np.arange(1,6)
print(a)

# this is the mask:
mask = [True, True, False, True, False]

# lets apply the mask:
print(a[mask])

[1 2 3 4 5]
[1 2 4]


#### Masking example 1 : select only the even values

In [40]:
# let's have a bigger array:
a = np.arange(1,20)

# and get only even numbers from it:
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

How it works:

a%2 is calculated for each element of the array.

If result value, which serves as index, is True => the element is selected, 
if it is False the element is not selected 

#### Masking example 2 : map list elements to array of indexes

In [41]:
# let's have a numpy array of repeated values 0, 1 or 2:
indexes = np.array([0, 2, 1, 2, 0, 1,2])

# and a list of colors:
colors = ['red', 'green', 'blue']

# let's group the elements of the 'indexes' array by color, according to 
# their values, which will be used as indexes in colors list
# For simplicity, we'll just print the groups, but if we need, we can save them in dictionary
for i in range(len(colors)):  
    print(f"{colors[i]} group:")
    print(indexes[indexes==i])
    

red group:
[0 0]
green group:
[1 1]
blue group:
[2 2 2]


#### Masking example 3 : group 'scores' by category

Let's have an array of 'scores', and for each score we'll have to assign a category from a predefined list. So, we'll add to each score element the index of the category list.
The goal is to group scores by category.

In [42]:
scores = np.array([
    [4, 1],
    [2, 0],
    [3, 0],
    [5, 1],
    [6, 1]
])

categories = ['bad', 'good']


for i in range(len(categories)):  
    # make the mask:
    mask = scores[:,1] == i
#     print(mask)
    
    # now apply it to scores:
    print(f"\n{categories[i]} scores are:")
    print(scores[mask,0])


bad scores are:
[2 3]

good scores are:
[4 5 6]
