In [11]:
import numpy as np

# Numpy Array Sorting



## Overview of sorting algorithms

In computer science there are varios sorting algorithms. 

One of the simlest is Bubble Sort:

![bubble_sort.gif](../images/bubble_sort.gif)

But while easy to understend and implement it is not quite efficient.

### The Big-0 Notation

Simply said, Big-O notation tells how much time your algorithm will take as we increase the amount of data. 
If you have an O[N] algorithm that takes 1 second to operate on a list of length N=1,000, then you should expect it to take roughly 5 seconds for a list of length N=5,000. 
If you have an O[N^2] ("order N squared") algorithm that takes 1 second for N=1000, then you should expect it to take about 25 seconds for N=5000.

![alt](../images/sorting_algorithms_comparison.jpeg)

Python has built-in sort and sorted functions to sort lists, but these functions are not eficient on numpy arrays.

Fortunatelly, numpy has its own array sorting methods.



## Fast Sorting in NumPy np.sort() and np.argsort()



### np.sort()

Basic Syntas:

`numpy.sort(a, axis=- 1, kind=None, order=None)[source]`

Reference: https://numpy.org/doc/stable/reference/generated/numpy.sort.html


By default np.sort() uses an O[NlogN], quicksort algorithm, though mergesort and heapsort are also available.

Note that using np.sort() method **the original array will not be sorted**, but a new sorted array will be returned.
If you want to sort array in place, you can use ndarray.sort() method wich **sorts an array in-place**

In [17]:
rng = np.random.default_rng(42)

arr = rng.integers(1,10,10)
arr

array([1, 7, 6, 4, 4, 8, 1, 7, 2, 1])

In [22]:
### sort as new array
arr_sorted = np.sort(arr)
arr_sorted

array([1, 1, 1, 2, 4, 4, 6, 7, 7, 8])

In [20]:
# not that original array is not changed
arr

array([1, 7, 6, 4, 4, 8, 1, 7, 2, 1])

In [23]:
arr2 = rng.integers(1,10,10)
arr2

array([5, 4, 2, 9, 8, 6, 4, 8, 5, 4])

In [25]:
### sort in-place:
arr2.sort()
arr2

array([2, 4, 4, 4, 5, 5, 6, 8, 8, 9])

#### Sort along axes

In [28]:
a2d = rng.integers(1,10,(3,4))
a2d

array([[7, 4, 1, 9],
       [5, 9, 7, 8],
       [7, 2, 4, 5]])

In [33]:
### sort each column:
np.sort(a2d, axis=0)

array([[5, 2, 1, 5],
       [7, 4, 4, 8],
       [7, 9, 7, 9]])

In [34]:
### sort each row:
np.sort(a2d, axis=1)

array([[1, 4, 7, 9],
       [5, 7, 8, 9],
       [2, 4, 5, 7]])

### np.argsort()

Returns the indices that would sort an array

In [36]:
arr = rng.integers(1,10,10)
arr

array([5, 1, 5, 2, 7, 7, 9, 7, 4, 9])

In [38]:
np.argsort(arr)

# note, that return value are the indexes that would sort the array

array([1, 3, 8, 0, 2, 4, 5, 7, 6, 9])

### Partial Sorts: np.partition()

Sometimes we don't need to sort the entire array, but simply want to find the k smallest values in the array. NumPy provides this in the np.partition method.

Basic Syntax:

numpy.partition(a, kth, axis=- 1, kind='introselect', order=None)[source]




Reference: https://numpy.org/doc/stable/reference/generated/numpy.partition.html#numpy.partition

In [39]:
arr = rng.integers(1,10,10)
arr

array([4, 3, 9, 4, 1, 5, 8, 2, 5, 2])

In [41]:
# get the first 3 least values from 1d array:

np.partition(arr, 3)

# note that the partion returned is not sorted by itself, by it contains the first 3 smallest number of arr

array([2, 1, 2, 3, 4, 4, 5, 9, 5, 8])