# Data Types

In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3])

In [5]:
arr.dtype

dtype('int64')

Data types are available as np.bool_, np.float32, etc.

In [7]:
arr = np.array([1,2,3], dtype=np.bool_)

In [8]:
arr.dtype

dtype('bool')

Data types can also be referred to by character codes, mostly to retain backward compatibility with older packages such as Numeric.

In [14]:
arr = np.array([1,2,3], dtype='?')
arr.dtype

dtype('bool')

Data-types can be used as functions to convert from one data type to another

In [9]:
arr = np.array([1,2,3])
arr.dtype

dtype('int64')

In [11]:
np.bool_(arr)

array([ True,  True,  True])

In [12]:
np.float64(arr)

array([1., 2., 3.])

To convert the type of an array, use the .astype() method, which is preffered than using dtypes as functions 

In [15]:
arr = np.array([1,2,3])
arr.dtype

dtype('int64')

In [16]:
arr.astype(np.bool_)

array([ True,  True,  True])

In [19]:
arr.astype(np.float64)

array([1., 2., 3.])