In [1]:
import numpy as np

# Numpy: image processing

## Overview

 An image is made up of a grid of pixels, with each pixel representing a specific color. When you view an image on a computer, the pixels are displayed on the screen, creating the visual representation of the image.

 For example, consider a simple **black and white image** that is 6 pixels wide and 6 pixels tall. It might look something like this:

 <img src="../images/ImageBitsRepresentation_Black_White-face.png" alt="ImageBitsRepresentation_Black_White" style="height:200px">

 Color images are represented as three-dimensional arrays of value for each pixel:

 <img src="../images/ImageBitsRepresentation_Color.png" alt="ImageBitsRepresentation_Color" style="height:300px">

 In order to perform operations on images, such as image processing or machine learning tasks, we often need to convert them into a numerical representation that can be processed by a computer. One way to do this is to convert the image into a numpy array.

## Convert image into numpy array with OpenCV

### What is OpenCV?

OpenCV (Open Source Computer Vision) is a free and open-source library of computer vision and machine learning algorithms designed to help developers build computer vision applications.

OpenCV contains a wide range of refunctions and utilities for image and video processing, including feature detection and extraction, object detection and cognition, and image and video manipulation. It is written in C++ and has bindings for many programming languages, including Python, Java, and C#.

OpenCV is widely used in a variety of applications, including robotics, self-driving cars, and security systems. It is a powerful tool for building computer vision applications and can be used in a variety of industries, including 
healthcare, finance, and retail.

### Install OpenCV in Python

Make sure your are in desired virtual env, open a terminal and type the following command:

``pip install opencv-python``

### Read an image with OpenCV

Next code will read the image file 'number_0.png' and output a NumPy 3D array with dimensions [height, width, channels], where height is the number of rows, width is the number of columns, and channels is the number of color channels (e.g., red, green, and blue).

Note, that OpenCV uses BGR(blue, green, red), instead of RGB(red, green, blue).

In [6]:
import cv2
import numpy as np

# Read the image file
image = cv2.imread('number_0.png')

# Convert the image to a NumPy array
image = np.array(image)

print(image)

[[[255   0   0]
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  [255 255 255]]]
